### ISSUE TITLE
incorrect displayed values for Tool Flutes & chipload

### ISSUE THREAD

**Issue by spanner888** [dubstar-04/FeedsAndSpeeds#13]
If in FC the ToolController Toolbit Flutes is 0, GUI opens showing value of "1". Similarly Chipload shows 0.020 when TC.Tool.Chipload = 0.

Edit: If number flutes=0, then will hfeed=0, so maybe should be set to 1, or ask user.

The chipload issue has been staring me in the face for long time, as there is already a print showing that.

To reproduce: Create a new doc, new part cube, cut a cylinder, new job using cut, without using template and without using any existing tools. Only using default TC/TB. examine TC & TB props in FC path and values shown in FS calc.

**Comment by dubstar-04** [comment]
I don't think it makes sense to support cutting tools with 0 flutes. As you need at least 1 flute to cut?

**Comment by dubstar-04** [comment]
Happy for you to change my mind on this if there is a use case.
