### ISSUE TITLE
Spindle speed being set too high when manually set from dialog

### ISSUE THREAD

**Issue by dresco** [dubstar-04/FeedsAndSpeeds#42]
Hi, when manually setting the spindle speed in the dialog, it seems to get saved as 10x too high, see below;
  
![image](https://user-images.githubusercontent.com/996823/155841583-86e6bded-34ce-400f-977e-bf296586b466.png)

**Comment by dubstar-04** [comment]
Thanks for reporting this. Can you let me know what unit settings you currently have in preferences?

**Comment by dresco** [comment]
Metric small parts, 3 decimal places.. Thanks!

**Comment by dubstar-04** [comment]
I think that's fixed now. Could you update from the addon manager and test?

**Comment by dresco** [comment]
That's great. Have updated to v0.4.0 & is working fine now. Many thanks!
