### ISSUE TITLE
Is FeedsAndSpeeds ready for FreeCAD 1.0 Release?

### ISSUE THREAD

**Issue by luzpaz** [dubstar-04/FeedsAndSpeeds#56]
* https://github.com/FreeCAD/Addons/issues/13

**Comment by luzpaz** [comment]
bump @dubstar-04

**Comment by JipeB** [comment]
Hello, a solution here [https://forum.freecad.org/viewtopic.php?t=92035](url)
or here for french speakers :[https://forum.freecad.org/viewtopic.php?t=92192](url)

**Comment by dubstar-04** [comment]
Updated to work with FreeCAD 1.0 in FreeCAD/FreeCAD-addons#57
