### ISSUE TITLE
Incorrect rpm return value in FSCalculation.calculation

### ISSUE THREAD

**Issue by spanner888** [dubstar-04/FeedsAndSpeeds#7]
While scripting with your great addon, I noticed that overrides of rpm where being ignored in returned rpm.

Cause seems to be return variable is "rpm", but "calc_rpm" is used if rpm override is triggered and also used for all the calculations, but then "rpm" is used in the return.

I have not submitted pull request, as I feel which way fix is implemented might be more a matter of personal taste, but happy to submit if your prefer.

**Comment by dubstar-04** [comment]
Fixed with #11
